# Basic docker-compose.yml running the project as docker container.
# Configuration of needed parameters can be done via ./.env file.
# This file isn't loaded into the image, just used as a source for environment variables.

version: "3.9"
services:
  chatgpt-discord-bot:
    image: chatgpt-discord-bot:latest
    build: .
    container_name: chatgpt-discord-bot
    restart: unless-stopped
    env_file: .env
    environment:
      - SOURCES_PERSISTENCE_FILE=persistence
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
networks:
  default:
    name: chatgpt-discord-bot-network
    driver: bridge

